/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import view.pageLogin;
import controller.perusahaanController;

public class pagePerusahaan extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(pagePerusahaan.class.getName());
    private perusahaanController controller;

    /**
     * Creates new form pagePerusahaan
     */
    public pagePerusahaan() {
        initComponents();
        controller = new perusahaanController(this);
        btnTambah.addActionListener(e -> controller.tambahLowongan());
        btnUbah.addActionListener(e -> controller.ubahLowongan());
        btnHapus.addActionListener(e -> controller.hapusLowongan());
        btnClear.addActionListener(e -> controller.clearForm());

        tableLowongan.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                controller.pilihBaris();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMenu = new javax.swing.JPanel();
        btnLowongan = new javax.swing.JButton();
        btnKelolaLamar = new javax.swing.JButton();
        btnRating = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        menu = new javax.swing.JLabel();
        panelKontainer = new javax.swing.JPanel();
        panelKelolaLowongan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textGaji = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textJobdesk = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        boxKontrak = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        textPosisi = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableLowongan = new javax.swing.JTable();
        panelPelamar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePelamar = new javax.swing.JTable();
        boxStatus = new javax.swing.JComboBox<>();
        btnCetak = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        panelRatingUlasan = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUlasan = new javax.swing.JTable();
        avgLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(950, 800));
        setPreferredSize(new java.awt.Dimension(950, 800));

        panelMenu.setBackground(new java.awt.Color(102, 102, 255));

        btnLowongan.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnLowongan.setText("Kelola Lowongan");
        btnLowongan.addActionListener(this::btnLowonganActionPerformed);

        btnKelolaLamar.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnKelolaLamar.setText("Pelamar Masuk");
        btnKelolaLamar.addActionListener(this::btnKelolaLamarActionPerformed);

        btnRating.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        btnRating.setText("Rating & Ulasan");
        btnRating.addActionListener(this::btnRatingActionPerformed);

        btnLogOut.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(this::btnLogOutActionPerformed);

        menu.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        menu.setText("MENU");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(menu)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnLowongan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRating, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKelolaLamar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(menu)
                .addGap(150, 150, 150)
                .addComponent(btnLogOut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMenuLayout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addComponent(btnLowongan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(btnKelolaLamar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(btnRating, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(684, Short.MAX_VALUE)))
        );

        panelKontainer.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel1.setText("Posisi");

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel8.setText("Jobdesk");

        textGaji.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel7.setText("Jenis Kontrak");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel5.setText("Kelola Lowongan");

        textJobdesk.setColumns(20);
        textJobdesk.setRows(5);
        jScrollPane2.setViewportView(textJobdesk);

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        jLabel6.setText("Gaji");

        boxKontrak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tetap", "Kontrak", "Magang" }));

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnTambah.setText("Tambah");

        btnUbah.setText("Ubah");

        textPosisi.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N

        btnHapus.setText("Hapus");

        tableLowongan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Lowongan", "Posisi", "Gaji", "Jenis Kontrak"
            }
        ));
        jScrollPane3.setViewportView(tableLowongan);

        javax.swing.GroupLayout panelKelolaLowonganLayout = new javax.swing.GroupLayout(panelKelolaLowongan);
        panelKelolaLowongan.setLayout(panelKelolaLowonganLayout);
        panelKelolaLowonganLayout.setHorizontalGroup(
            panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKelolaLowonganLayout.createSequentialGroup()
                .addGroup(panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKelolaLowonganLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelKelolaLowonganLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addGap(12, 12, 12)
                        .addGroup(panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxKontrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textGaji, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textPosisi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(panelKelolaLowonganLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        panelKelolaLowonganLayout.setVerticalGroup(
            panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKelolaLowonganLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addGroup(panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textPosisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(boxKontrak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelKelolaLowonganLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        panelKontainer.add(panelKelolaLowongan, "halamanKelolaLowongan");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setText("Pelamar Masuk");

        tablePelamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pelamar", "Email", "No HP", "Posisi ", "Tanggal Lamar", "Status"
            }
        ));
        jScrollPane4.setViewportView(tablePelamar);

        boxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Diproses", "Diterima", "Ditolak" }));

        btnCetak.setText("Cetak ");
        btnCetak.addActionListener(this::btnCetakActionPerformed);

        btnUpdate.setText("Update Status");

        javax.swing.GroupLayout panelPelamarLayout = new javax.swing.GroupLayout(panelPelamar);
        panelPelamar.setLayout(panelPelamarLayout);
        panelPelamarLayout.setHorizontalGroup(
            panelPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPelamarLayout.createSequentialGroup()
                .addGroup(panelPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPelamarLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate)
                            .addComponent(btnCetak)))
                    .addGroup(panelPelamarLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel9)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        panelPelamarLayout.setVerticalGroup(
            panelPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPelamarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(panelPelamarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPelamarLayout.createSequentialGroup()
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCetak)
                        .addGap(18, 18, 18)
                        .addComponent(boxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(343, Short.MAX_VALUE))
        );

        panelKontainer.add(panelPelamar, "halamanPelamar");

        tableUlasan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Tanggal Ulasan", "Skor Bintang", "Isi Ulasan"
            }
        ));
        jScrollPane1.setViewportView(tableUlasan);

        avgLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        avgLabel.setText("Rating Budaya Kerja Anda: 4.5/5");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("Rating & Ulasan");

        javax.swing.GroupLayout panelRatingUlasanLayout = new javax.swing.GroupLayout(panelRatingUlasan);
        panelRatingUlasan.setLayout(panelRatingUlasanLayout);
        panelRatingUlasanLayout.setHorizontalGroup(
            panelRatingUlasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRatingUlasanLayout.createSequentialGroup()
                .addGroup(panelRatingUlasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRatingUlasanLayout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(panelRatingUlasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRatingUlasanLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jLabel3))
                            .addComponent(avgLabel)))
                    .addGroup(panelRatingUlasanLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(275, Short.MAX_VALUE))
        );
        panelRatingUlasanLayout.setVerticalGroup(
            panelRatingUlasanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRatingUlasanLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avgLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(365, Short.MAX_VALUE))
        );

        panelKontainer.add(panelRatingUlasan, "halamanRating");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelKontainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelKontainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        this.dispose();
        new pageLogin().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnLowonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLowonganActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontainer.getLayout();
        cl.show(panelKontainer, "halamanKelolaLowongan");
    }//GEN-LAST:event_btnLowonganActionPerformed

    private void btnKelolaLamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaLamarActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontainer.getLayout();
        cl.show(panelKontainer, "halamanPelamar");
    }//GEN-LAST:event_btnKelolaLamarActionPerformed

    private void btnRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRatingActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout) panelKontainer.getLayout();
        cl.show(panelKontainer, "halamanRating");
    }//GEN-LAST:event_btnRatingActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new pagePerusahaan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel avgLabel;
    public javax.swing.JComboBox<String> boxKontrak;
    public javax.swing.JComboBox<String> boxStatus;
    public javax.swing.JButton btnCetak;
    public javax.swing.JButton btnClear;
    public javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKelolaLamar;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnLowongan;
    private javax.swing.JButton btnRating;
    public javax.swing.JButton btnTambah;
    public javax.swing.JButton btnUbah;
    public javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel menu;
    private javax.swing.JPanel panelKelolaLowongan;
    private javax.swing.JPanel panelKontainer;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPelamar;
    private javax.swing.JPanel panelRatingUlasan;
    public javax.swing.JTable tableLowongan;
    public javax.swing.JTable tablePelamar;
    public javax.swing.JTable tableUlasan;
    public javax.swing.JTextField textGaji;
    public javax.swing.JTextArea textJobdesk;
    public javax.swing.JTextField textPosisi;
    // End of variables declaration//GEN-END:variables
}
